[package]
name = "rust-bstree-file"
version = "0.1.0"
authors = ["pineau <francois-xavier.pineau@astro.unistra.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
